extends: airbnb
env:
  node: true
  browser: true
  jest: true
rules:
  strict: 0
  global-require: 0
  react/jsx-one-expression-per-line: 0
  key-spacing:
    - error
    - align: value
  no-multi-spaces:
    - error
    - exceptions:
        VariableDeclarator: true
        ImportDeclaration: true
  import/no-extraneous-dependencies: 0
  no-unused-vars:
    - error
    - argsIgnorePattern: "next"
  no-param-reassign:
    - error
    - props: false
  no-console: 0
